#!/usr/bin/env bash
#
# Deploy the built site to the `recall` Vercel project.
#
# The output directory is regenerated by every build, so a .vercel link inside
# it does not survive. The project is identified by id through the environment
# instead — otherwise the CLI infers a project from the directory name and
# silently creates a new one ("out") with its own URL.
#
#   scripts/deploy.sh          deploy site-next/out to production
#
# Deployment protection: a fresh Vercel project has SSO protection ON, which
# makes every URL 302 to vercel.com/sso-api — a login wall for anyone you send
# the link to. This script clears it after deploying and verifies the result.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${1:-site-next/out}"
[[ -f "$OUT/index.html" ]] || { echo "no $OUT/index.html — run scripts/build-site.sh first" >&2; exit 1; }

LINK="$ROOT/.vercel-project.json"
[[ -f "$LINK" ]] || { echo "missing $LINK (projectId + orgId)" >&2; exit 1; }

export VERCEL_ORG_ID="$(node -p "require('$LINK').orgId")"
export VERCEL_PROJECT_ID="$(node -p "require('$LINK').projectId")"
TOKEN="$(node -p "require(require('os').homedir()+'/.local/share/com.vercel.cli/auth.json').token")"

echo "── deploying $OUT to project $VERCEL_PROJECT_ID"
URL="$(cd "$OUT" && vercel deploy --prod --yes 2>&1 | grep -oE 'https://[a-z0-9.-]+vercel\.app' | tail -1)"
echo "   $URL"

echo "── clearing deployment protection"
curl -fsS -X PATCH \
  "https://api.vercel.com/v9/projects/$VERCEL_PROJECT_ID?teamId=$VERCEL_ORG_ID" \
  -H "Authorization: Bearer $TOKEN" \
  -H "content-type: application/json" \
  -d '{"ssoProtection":null}' > /dev/null

sleep 3
for path in / /app/ /site.json /demo.json; do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$URL$path")"
  printf '   %s  %s\n' "$code" "$path"
  [[ "$code" == "200" ]] || echo "   ! expected 200" >&2
done

echo
echo "live: $URL"
