#!/usr/bin/env bash
#
# Deploy the built site to the `recall` Vercel project.
#
# The output directory is regenerated by every build, so a .vercel link inside
# it does not survive. The project is identified by id through the environment
# instead — otherwise the CLI infers a project from the directory name and
# silently creates a new one ("out") with its own URL.
#
#   scripts/deploy.sh          deploy site-next/out to production
#
# Deployment protection: a fresh Vercel project has SSO protection ON, which
# makes every URL 302 to vercel.com/sso-api — a login wall for anyone you send
# the link to. This script clears it after deploying and verifies the result.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

OUT="${1:-site-next/out}"
[[ -f "$OUT/index.html" ]] || { echo "no $OUT/index.html — run scripts/build-site.sh first" >&2; exit 1; }

LINK="$ROOT/.vercel-project.json"
[[ -f "$LINK" ]] || { echo "missing $LINK (projectId + orgId)" >&2; exit 1; }

export VERCEL_ORG_ID="$(node -p "require('$LINK').orgId")"
export VERCEL_PROJECT_ID="$(node -p "require('$LINK').projectId")"

echo "── deploying $OUT to project $VERCEL_PROJECT_ID"
URL="$(cd "$OUT" && vercel deploy --prod --yes 2>&1 | grep -oE 'https://[a-z0-9.-]+vercel\.app' | tail -1)"
echo "   $URL"

echo "── clearing deployment protection"
# The token is read HERE, after the deploy — not before it. `vercel deploy`
# refreshes the CLI's OAuth token, so a copy taken earlier in the script is
# already stale by this point and the PATCH comes back 403 with the clearing
# silently skipped. That is how a login wall reaches a judge.
API="https://api.vercel.com/v9/projects/$VERCEL_PROJECT_ID?teamId=$VERCEL_ORG_ID"
TOKEN="$(node -p "require(require('os').homedir()+'/.local/share/com.vercel.cli/auth.json').token")"

code="$(curl -s -o /tmp/vercel-protection.json -w '%{http_code}' -X PATCH "$API" \
  -H "Authorization: Bearer $TOKEN" \
  -H "content-type: application/json" \
  -d '{"ssoProtection":null}')"

if [[ "$code" != "200" ]]; then
  echo "   ! PATCH returned $code — $(node -p "try{JSON.parse(require('fs').readFileSync('/tmp/vercel-protection.json','utf8')).error?.message ?? ''}catch(e){''}")" >&2
fi

# Verify from the API rather than assuming the write landed.
curl -s -o /tmp/vercel-project.json "$API" -H "Authorization: Bearer $TOKEN" || true
node -e '
  let p = {};
  try { p = JSON.parse(require("fs").readFileSync("/tmp/vercel-project.json", "utf8")); } catch {}
  const sso = p.ssoProtection ?? null, pw = p.passwordProtection ?? null;
  if (sso === null && pw === null) console.log("   protection: off");
  else { console.error("   ! still protected:", JSON.stringify({ sso, pw }), "— judges will hit a login wall"); process.exit(1); }
'

sleep 3
for path in / /app/ /site.json /demo.json; do
  code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 30 "$URL$path")"
  printf '   %s  %s\n' "$code" "$path"
  [[ "$code" == "200" ]] || echo "   ! expected 200" >&2
done

echo
echo "live: $URL"
